services:
  employr-api:
    build:
      context: .
      dockerfile: Dockerfile
      target: api
    image: employr-api:latest
    container_name: employr-api
    restart: unless-stopped
    # ponytail: share postgres dgn mfood, beda database
    environment:
      NODE_ENV: production
      DATABASE_URL: "postgresql://cuti:${CUTI_DB_PASSWORD}@cwj5rpthgiaz8v9k0gn1x5mu:5432/cuti"
      JWT_SECRET: "${CUTI_JWT_SECRET}"
      JWT_EXPIRES_IN: "7d"
    networks: [coolify]

  employr-admin:
    build:
      context: .
      dockerfile: Dockerfile
      target: admin
    image: employr-admin:latest
    container_name: employr-admin
    restart: unless-stopped
    environment:
      NODE_ENV: production
      DATABASE_URL: "postgresql://cuti:${CUTI_DB_PASSWORD}@cwj5rpthgiaz8v9k0gn1x5mu:5432/cuti"
      JWT_SECRET: "${CUTI_JWT_SECRET}"
      ADMIN_SESSION_SECRET: "${CUTI_JWT_SECRET}"
    networks: [coolify]

  employr-dashboard:
    build:
      context: .
      dockerfile: Dockerfile
      target: dashboard
    image: employr-dashboard:latest
    container_name: employr-dashboard
    restart: unless-stopped
    environment:
      NODE_ENV: production
      DATABASE_URL: "postgresql://cuti:${CUTI_DB_PASSWORD}@cwj5rpthgiaz8v9k0gn1x5mu:5432/cuti"
      JWT_SECRET: "${CUTI_JWT_SECRET}"
    networks: [coolify]

networks:
  coolify:
    external: true
