/**
 * Data Kota & Kabupaten di Indonesia berdasarkan data BPS / Kemendagri (cahyadsn/wilayah).
 * Meliputi 38 Provinsi dengan 514 Kota & Kabupaten.
 */
export const INDONESIAN_CITIES: string[] = [
  // DKI Jakarta
  'Kota Jakarta Selatan, DKI Jakarta',
  'Kota Jakarta Pusat, DKI Jakarta',
  'Kota Jakarta Barat, DKI Jakarta',
  'Kota Jakarta Timur, DKI Jakarta',
  'Kota Jakarta Utara, DKI Jakarta',
  'Kab. Kepulauan Seribu, DKI Jakarta',

  // Jawa Barat
  'Kota Bandung, Jawa Barat',
  'Kota Bogor, Jawa Barat',
  'Kota Bekasi, Jawa Barat',
  'Kota Depok, Jawa Barat',
  'Kota Cimahi, Jawa Barat',
  'Kota Cirebon, Jawa Barat',
  'Kota Sukabumi, Jawa Barat',
  'Kota Tasikmalaya, Jawa Barat',
  'Kota Banjar, Jawa Barat',
  'Kab. Bandung, Jawa Barat',
  'Kab. Bandung Barat, Jawa Barat',
  'Kab. Bogor, Jawa Barat',
  'Kab. Bekasi, Jawa Barat',
  'Kab. Cirebon, Jawa Barat',
  'Kab. Sukabumi, Jawa Barat',
  'Kab. Tasikmalaya, Jawa Barat',
  'Kab. Garut, Jawa Barat',
  'Kab. Cianjur, Jawa Barat',
  'Kab. Indramayu, Jawa Barat',
  'Kab. Karawang, Jawa Barat',
  'Kab. Kuningan, Jawa Barat',
  'Kab. Majalengka, Jawa Barat',
  'Kab. Purwakarta, Jawa Barat',
  'Kab. Subang, Jawa Barat',
  'Kab. Sumedang, Jawa Barat',
  'Kab. Ciamis, Jawa Barat',
  'Kab. Pangandaran, Jawa Barat',

  // Banten
  'Kota Tangerang, Banten',
  'Kota Tangerang Selatan, Banten',
  'Kota Serang, Banten',
  'Kota Cilegon, Banten',
  'Kab. Tangerang, Banten',
  'Kab. Serang, Banten',
  'Kab. Lebak, Banten',
  'Kab. Pandeglang, Banten',

  // Jawa Tengah
  'Kota Semarang, Jawa Tengah',
  'Kota Surakarta (Solo), Jawa Tengah',
  'Kota Magelang, Jawa Tengah',
  'Kota Pekalongan, Jawa Tengah',
  'Kota Salatiga, Jawa Tengah',
  'Kota Tegal, Jawa Tengah',
  'Kab. Semarang, Jawa Tengah',
  'Kab. Magelang, Jawa Tengah',
  'Kab. Boyolali, Jawa Tengah',
  'Kab. Klaten, Jawa Tengah',
  'Kab. Sukoharjo, Jawa Tengah',
  'Kab. Karanganyar, Jawa Tengah',
  'Kab. Sragen, Jawa Tengah',
  'Kab. Wonogiri, Jawa Tengah',
  'Kab. Grobogan, Jawa Tengah',
  'Kab. Blora, Jawa Tengah',
  'Kab. Rembang, Jawa Tengah',
  'Kab. Pati, Jawa Tengah',
  'Kab. Kudus, Jawa Tengah',
  'Kab. Jepara, Jawa Tengah',
  'Kab. Demak, Jawa Tengah',
  'Kab. Temanggung, Jawa Tengah',
  'Kab. Kendal, Jawa Tengah',
  'Kab. Batang, Jawa Tengah',
  'Kab. Pekalongan, Jawa Tengah',
  'Kab. Pemalang, Jawa Tengah',
  'Kab. Tegal, Jawa Tengah',
  'Kab. Brebes, Jawa Tengah',
  'Kab. Banyumas, Jawa Tengah',
  'Kab. Cilacap, Jawa Tengah',
  'Kab. Purbalingga, Jawa Tengah',
  'Kab. Banjarnegara, Jawa Tengah',
  'Kab. Kebumen, Jawa Tengah',
  'Kab. Purworejo, Jawa Tengah',
  'Kab. Wonosobo, Jawa Tengah',

  // D.I. Yogyakarta
  'Kota Yogyakarta, D.I. Yogyakarta',
  'Kab. Sleman, D.I. Yogyakarta',
  'Kab. Bantul, D.I. Yogyakarta',
  'Kab. Gunungkidul, D.I. Yogyakarta',
  'Kab. Kulon Progo, D.I. Yogyakarta',

  // Jawa Timur
  'Kota Surabaya, Jawa Timur',
  'Kota Malang, Jawa Timur',
  'Kota Batu, Jawa Timur',
  'Kota Kediri, Jawa Timur',
  'Kota Blitar, Jawa Timur',
  'Kota Madiun, Jawa Timur',
  'Kota Mojokerto, Jawa Timur',
  'Kota Pasuruan, Jawa Timur',
  'Kota Probolinggo, Jawa Timur',
  'Kab. Malang, Jawa Timur',
  'Kab. Sidoarjo, Jawa Timur',
  'Kab. Gresik, Jawa Timur',
  'Kab. Pasuruan, Jawa Timur',
  'Kab. Probolinggo, Jawa Timur',
  'Kab. Mojokerto, Jawa Timur',
  'Kab. Jombang, Jawa Timur',
  'Kab. Nganjuk, Jawa Timur',
  'Kab. Madiun, Jawa Timur',
  'Kab. Magetan, Jawa Timur',
  'Kab. Ngawi, Jawa Timur',
  'Kab. Ponorogo, Jawa Timur',
  'Kab. Pacitan, Jawa Timur',
  'Kab. Kediri, Jawa Timur',
  'Kab. Blitar, Jawa Timur',
  'Kab. Tulungagung, Jawa Timur',
  'Kab. Trenggalek, Jawa Timur',
  'Kab. Tuban, Jawa Timur',
  'Kab. Lamongan, Jawa Timur',
  'Kab. Bojonegoro, Jawa Timur',
  'Kab. Lumajang, Jawa Timur',
  'Kab. Jember, Jawa Timur',
  'Kab. Bondowoso, Jawa Timur',
  'Kab. Situbondo, Jawa Timur',
  'Kab. Banyuwangi, Jawa Timur',
  'Kab. Bangkalan, Jawa Timur',
  'Kab. Sampang, Jawa Timur',
  'Kab. Pamekasan, Jawa Timur',
  'Kab. Sumenep, Jawa Timur',

  // Bali
  'Kota Denpasar, Bali',
  'Kab. Badung, Bali',
  'Kab. Gianyar, Bali',
  'Kab. Tabanan, Bali',
  'Kab. Buleleng, Bali',
  'Kab. Karangasem, Bali',
  'Kab. Klungkung, Bali',
  'Kab. Bangli, Bali',
  'Kab. Jembrana, Bali',

  // Nusa Tenggara Barat (NTB)
  'Kota Mataram, Nusa Tenggara Barat',
  'Kota Bima, Nusa Tenggara Barat',
  'Kab. Lombok Barat, Nusa Tenggara Barat',
  'Kab. Lombok Tengah, Nusa Tenggara Barat',
  'Kab. Lombok Timur, Nusa Tenggara Barat',
  'Kab. Lombok Utara, Nusa Tenggara Barat',
  'Kab. Sumbawa, Nusa Tenggara Barat',
  'Kab. Sumbawa Barat, Nusa Tenggara Barat',
  'Kab. Dompu, Nusa Tenggara Barat',
  'Kab. Bima, Nusa Tenggara Barat',

  // Nusa Tenggara Timur (NTT)
  'Kota Kupang, Nusa Tenggara Timur',
  'Kab. Kupang, Nusa Tenggara Timur',
  'Kab. Timor Tengah Selatan, Nusa Tenggara Timur',
  'Kab. Timor Tengah Utara, Nusa Tenggara Timur',
  'Kab. Belu, Nusa Tenggara Timur',
  'Kab. Malaka, Nusa Tenggara Timur',
  'Kab. Rote Ndao, Nusa Tenggara Timur',
  'Kab. Sabu Raijua, Nusa Tenggara Timur',
  'Kab. Alor, Nusa Tenggara Timur',
  'Kab. Flores Timur, Nusa Tenggara Timur',
  'Kab. Sikka, Nusa Tenggara Timur',
  'Kab. Ende, Nusa Tenggara Timur',
  'Kab. Ngada, Nusa Tenggara Timur',
  'Kab. Nagekeo, Nusa Tenggara Timur',
  'Kab. Manggarai, Nusa Tenggara Timur',
  'Kab. Manggarai Barat, Nusa Tenggara Timur',
  'Kab. Manggarai Timur, Nusa Tenggara Timur',
  'Kab. Sumba Barat, Nusa Tenggara Timur',
  'Kab. Sumba Barat Daya, Nusa Tenggara Timur',
  'Kab. Sumba Tengah, Nusa Tenggara Timur',
  'Kab. Sumba Timur, Nusa Tenggara Timur',
  'Kab. Lembata, Nusa Tenggara Timur',

  // Sumatera Utara
  'Kota Medan, Sumatera Utara',
  'Kota Binjai, Sumatera Utara',
  'Kota Pematangsiantar, Sumatera Utara',
  'Kota Tanjungbalai, Sumatera Utara',
  'Kota Tebing Tinggi, Sumatera Utara',
  'Kota Sibolga, Sumatera Utara',
  'Kota Padangsidimpuan, Sumatera Utara',
  'Kota Gunungsitoli, Sumatera Utara',
  'Kab. Deli Serdang, Sumatera Utara',
  'Kab. Langkat, Sumatera Utara',
  'Kab. Karo, Sumatera Utara',
  'Kab. Simalungun, Sumatera Utara',
  'Kab. Asahan, Sumatera Utara',
  'Kab. Labuhanbatu, Sumatera Utara',
  'Kab. Dairi, Sumatera Utara',
  'Kab. Tapanuli Utara, Sumatera Utara',
  'Kab. Tapanuli Selatan, Sumatera Utara',
  'Kab. Tapanuli Tengah, Sumatera Utara',
  'Kab. Nias, Sumatera Utara',
  'Kab. Nias Selatan, Sumatera Utara',
  'Kab. Nias Utara, Sumatera Utara',
  'Kab. Nias Barat, Sumatera Utara',
  'Kab. Mandailing Natal, Sumatera Utara',
  'Kab. Toba, Sumatera Utara',
  'Kab. Samosir, Sumatera Utara',
  'Kab. Humbang Hasundutan, Sumatera Utara',
  'Kab. Pakpak Bharat, Sumatera Utara',
  'Kab. Batubara, Sumatera Utara',
  'Kab. Padang Lawas, Sumatera Utara',
  'Kab. Padang Lawas Utara, Sumatera Utara',
  'Kab. Labuhanbatu Utara, Sumatera Utara',
  'Kab. Labuhanbatu Selatan, Sumatera Utara',
  'Kab. Serdang Bedagai, Sumatera Utara',

  // Sumatera Barat
  'Kota Padang, Sumatera Barat',
  'Kota Bukittinggi, Sumatera Barat',
  'Kota Payakumbuh, Sumatera Barat',
  'Kota Solok, Sumatera Barat',
  'Kota Sawahlunto, Sumatera Barat',
  'Kota Padang Panjang, Sumatera Barat',
  'Kota Pariaman, Sumatera Barat',
  'Kab. Agam, Sumatera Barat',
  'Kab. Tanah Datar, Sumatera Barat',
  'Kab. Padang Pariaman, Sumatera Barat',
  'Kab. Solok, Sumatera Barat',
  'Kab. Solok Selatan, Sumatera Barat',
  'Kab. Pesisir Selatan, Sumatera Barat',
  'Kab. Pasaman, Sumatera Barat',
  'Kab. Pasaman Barat, Sumatera Barat',
  'Kab. Lima Puluh Kota, Sumatera Barat',
  'Kab. Sijunjung, Sumatera Barat',
  'Kab. Dharmasraya, Sumatera Barat',
  'Kab. Kepulauan Mentawai, Sumatera Barat',

  // Riau
  'Kota Pekanbaru, Riau',
  'Kota Dumai, Riau',
  'Kab. Kampar, Riau',
  'Kab. Bengkalis, Riau',
  'Kab. Indragiri Hulu, Riau',
  'Kab. Indragiri Hilir, Riau',
  'Kab. Pelalawan, Riau',
  'Kab. Rokan Hulu, Riau',
  'Kab. Rokan Hilir, Riau',
  'Kab. Siak, Riau',
  'Kab. Kuantan Singingi, Riau',
  'Kab. Kepulauan Meranti, Riau',

  // Kepulauan Riau
  'Kota Batam, Kepulauan Riau',
  'Kota Tanjungpinang, Kepulauan Riau',
  'Kab. Bintan, Kepulauan Riau',
  'Kab. Karimun, Kepulauan Riau',
  'Kab. Natuna, Kepulauan Riau',
  'Kab. Lingga, Kepulauan Riau',
  'Kab. Kepulauan Anambas, Kepulauan Riau',

  // Jambi
  'Kota Jambi, Jambi',
  'Kota Sungai Penuh, Jambi',
  'Kab. Muaro Jambi, Jambi',
  'Kab. Bungo, Jambi',
  'Kab. Tebo, Jambi',
  'Kab. Merangin, Jambi',
  'Kab. Sarolangun, Jambi',
  'Kab. Batanghari, Jambi',
  'Kab. Kerinci, Jambi',
  'Kab. Tanjung Jabung Barat, Jambi',
  'Kab. Tanjung Jabung Timur, Jambi',

  // Sumatera Selatan
  'Kota Palembang, Sumatera Selatan',
  'Kota Prabumulih, Sumatera Selatan',
  'Kota Pagar Alam, Sumatera Selatan',
  'Kota Lubuklinggau, Sumatera Selatan',
  'Kab. Ogan Komering Ilir, Sumatera Selatan',
  'Kab. Ogan Komering Ulu, Sumatera Selatan',
  'Kab. Ogan Komering Ulu Timur, Sumatera Selatan',
  'Kab. Ogan Komering Ulu Selatan, Sumatera Selatan',
  'Kab. Ogan Ilir, Sumatera Selatan',
  'Kab. Muara Enim, Sumatera Selatan',
  'Kab. Lahat, Sumatera Selatan',
  'Kab. Musi Rawas, Sumatera Selatan',
  'Kab. Musi Rawas Utara, Sumatera Selatan',
  'Kab. Musi Banyuasin, Sumatera Selatan',
  'Kab. Banyuasin, Sumatera Selatan',
  'Kab. Empat Lawang, Sumatera Selatan',
  'Kab. Penukal Abab Lematang Ilir, Sumatera Selatan',

  // Bengkulu
  'Kota Bengkulu, Bengkulu',
  'Kab. Bengkulu Utara, Bengkulu',
  'Kab. Bengkulu Selatan, Bengkulu',
  'Kab. Bengkulu Tengah, Bengkulu',
  'Kab. Rejang Lebong, Bengkulu',
  'Kab. Kepahiang, Bengkulu',
  'Kab. Lebong, Bengkulu',
  'Kab. Kaur, Bengkulu',
  'Kab. Seluma, Bengkulu',
  'Kab. Mukomuko, Bengkulu',

  // Lampung
  'Kota Bandar Lampung, Lampung',
  'Kota Metro, Lampung',
  'Kab. Lampung Selatan, Lampung',
  'Kab. Lampung Tengah, Lampung',
  'Kab. Lampung Utara, Lampung',
  'Kab. Lampung Barat, Lampung',
  'Kab. Lampung Timur, Lampung',
  'Kab. Tanggamus, Lampung',
  'Kab. Tulang Bawang, Lampung',
  'Kab. Tulang Bawang Barat, Lampung',
  'Kab. Way Kanan, Lampung',
  'Kab. Pesawaran, Lampung',
  'Kab. Pringsewu, Lampung',
  'Kab. Mesuji, Lampung',
  'Kab. Pesisir Barat, Lampung',

  // Bangka Belitung
  'Kota Pangkalpinang, Bangka Belitung',
  'Kab. Bangka, Bangka Belitung',
  'Kab. Bangka Barat, Bangka Belitung',
  'Kab. Bangka Tengah, Bangka Belitung',
  'Kab. Bangka Selatan, Bangka Belitung',
  'Kab. Belitung, Bangka Belitung',
  'Kab. Belitung Timur, Bangka Belitung',

  // Aceh
  'Kota Banda Aceh, Aceh',
  'Kota Lhokseumawe, Aceh',
  'Kota Langsa, Aceh',
  'Kota Subulussalam, Aceh',
  'Kota Sabang, Aceh',
  'Kab. Aceh Besar, Aceh',
  'Kab. Aceh Utara, Aceh',
  'Kab. Aceh Timur, Aceh',
  'Kab. Aceh Selatan, Aceh',
  'Kab. Aceh Barat, Aceh',
  'Kab. Aceh Tengah, Aceh',
  'Kab. Aceh Tenggara, Aceh',
  'Kab. Aceh Singkil, Aceh',
  'Kab. Bireuen, Aceh',
  'Kab. Simeulue, Aceh',
  'Kab. Pidie, Aceh',
  'Kab. Pidie Jaya, Aceh',
  'Kab. Aceh Jaya, Aceh',
  'Kab. Nagan Raya, Aceh',
  'Kab. Aceh Barat Daya, Aceh',
  'Kab. Gayo Lues, Aceh',
  'Kab. Bener Meriah, Aceh',
  'Kab. Aceh Tamiang, Aceh',

  // Kalimantan Barat
  'Kota Pontianak, Kalimantan Barat',
  'Kota Singkawang, Kalimantan Barat',
  'Kab. Kubu Raya, Kalimantan Barat',
  'Kab. Mempawah, Kalimantan Barat',
  'Kab. Sambas, Kalimantan Barat',
  'Kab. Bengkayang, Kalimantan Barat',
  'Kab. Landak, Kalimantan Barat',
  'Kab. Sanggau, Kalimantan Barat',
  'Kab. Sekadau, Kalimantan Barat',
  'Kab. Sintang, Kalimantan Barat',
  'Kab. Melawi, Kalimantan Barat',
  'Kab. Kapuas Hulu, Kalimantan Barat',
  'Kab. Kayong Utara, Kalimantan Barat',
  'Kab. Ketapang, Kalimantan Barat',

  // Kalimantan Tengah
  'Kota Palangkaraya, Kalimantan Tengah',
  'Kab. Kotawaringin Barat, Kalimantan Tengah',
  'Kab. Kotawaringin Timur, Kalimantan Tengah',
  'Kab. Kapuas, Kalimantan Tengah',
  'Kab. Barito Selatan, Kalimantan Tengah',
  'Kab. Barito Utara, Kalimantan Tengah',
  'Kab. Barito Timur, Kalimantan Tengah',
  'Kab. Murung Raya, Kalimantan Tengah',
  'Kab. Gunung Mas, Kalimantan Tengah',
  'Kab. Pulang Pisau, Kalimantan Tengah',
  'Kab. Katingan, Kalimantan Tengah',
  'Kab. Seruyan, Kalimantan Tengah',
  'Kab. Sukamara, Kalimantan Tengah',
  'Kab. Lamandau, Kalimantan Tengah',

  // Kalimantan Selatan
  'Kota Banjarmasin, Kalimantan Selatan',
  'Kota Banjarbaru, Kalimantan Selatan',
  'Kab. Banjar, Kalimantan Selatan',
  'Kab. Tanah Laut, Kalimantan Selatan',
  'Kab. Tanah Bumbu, Kalimantan Selatan',
  'Kab. Kotabaru, Kalimantan Selatan',
  'Kab. Barito Kuala, Kalimantan Selatan',
  'Kab. Tapin, Kalimantan Selatan',
  'Kab. Hulu Sungai Selatan, Kalimantan Selatan',
  'Kab. Hulu Sungai Tengah, Kalimantan Selatan',
  'Kab. Hulu Sungai Utara, Kalimantan Selatan',
  'Kab. Tabalong, Kalimantan Selatan',
  'Kab. Balangan, Kalimantan Selatan',

  // Kalimantan Timur
  'Kota Samarinda, Kalimantan Timur',
  'Kota Balikpapan, Kalimantan Timur',
  'Kota Bontang, Kalimantan Timur',
  'Kab. Kutai Kartanegara, Kalimantan Timur',
  'Kab. Kutai Timur, Kalimantan Timur',
  'Kab. Kutai Barat, Kalimantan Timur',
  'Kab. Berau, Kalimantan Timur',
  'Kab. Paser, Kalimantan Timur',
  'Kab. Penajam Paser Utara, Kalimantan Timur',
  'Kab. Mahakam Ulu, Kalimantan Timur',

  // Kalimantan Utara
  'Kota Tarakan, Kalimantan Utara',
  'Kab. Bulungan, Kalimantan Utara',
  'Kab. Nunukan, Kalimantan Utara',
  'Kab. Malinau, Kalimantan Utara',
  'Kab. Tana Tidung, Kalimantan Utara',

  // Sulawesi Utara
  'Kota Manado, Sulawesi Utara',
  'Kota Bitung, Sulawesi Utara',
  'Kota Tomohon, Sulawesi Utara',
  'Kota Kotamobagu, Sulawesi Utara',
  'Kab. Minahasa, Sulawesi Utara',
  'Kab. Minahasa Utara, Sulawesi Utara',
  'Kab. Minahasa Selatan, Sulawesi Utara',
  'Kab. Minahasa Tenggara, Sulawesi Utara',
  'Kab. Bolaang Mongondow, Sulawesi Utara',
  'Kab. Bolaang Mongondow Utara, Sulawesi Utara',
  'Kab. Bolaang Mongondow Selatan, Sulawesi Utara',
  'Kab. Bolaang Mongondow Timur, Sulawesi Utara',
  'Kab. Kepulauan Sangihe, Sulawesi Utara',
  'Kab. Kepulauan Talaud, Sulawesi Utara',
  'Kab. Kepulauan Siau Tagulandang Biaro, Sulawesi Utara',

  // Sulawesi Tengah
  'Kota Palu, Sulawesi Tengah',
  'Kab. Sigi, Sulawesi Tengah',
  'Kab. Donggala, Sulawesi Tengah',
  'Kab. Parigimoutong, Sulawesi Tengah',
  'Kab. Poso, Sulawesi Tengah',
  'Kab. Tojo Una-Una, Sulawesi Tengah',
  'Kab. Banggai, Sulawesi Tengah',
  'Kab. Banggai Kepulauan, Sulawesi Tengah',
  'Kab. Banggai Laut, Sulawesi Tengah',
  'Kab. Morowali, Sulawesi Tengah',
  'Kab. Morowali Utara, Sulawesi Tengah',
  'Kab. Buol, Sulawesi Tengah',
  'Kab. Tolitoli, Sulawesi Tengah',

  // Sulawesi Selatan
  'Kota Makassar, Sulawesi Selatan',
  'Kota Parepare, Sulawesi Selatan',
  'Kota Palopo, Sulawesi Selatan',
  'Kab. Gowa, Sulawesi Selatan',
  'Kab. Maros, Sulawesi Selatan',
  'Kab. Pangkajene dan Kepulauan, Sulawesi Selatan',
  'Kab. Barru, Sulawesi Selatan',
  'Kab. Bone, Sulawesi Selatan',
  'Kab. Soppeng, Sulawesi Selatan',
  'Kab. Wajo, Sulawesi Selatan',
  'Kab. Sidenreng Rappang, Sulawesi Selatan',
  'Kab. Pinrang, Sulawesi Selatan',
  'Kab. Enrekang, Sulawesi Selatan',
  'Kab. Luwu, Sulawesi Selatan',
  'Kab. Luwu Utara, Sulawesi Selatan',
  'Kab. Luwu Timur, Sulawesi Selatan',
  'Kab. Tana Toraja, Sulawesi Selatan',
  'Kab. Toraja Utara, Sulawesi Selatan',
  'Kab. Takalar, Sulawesi Selatan',
  'Kab. Jeneponto, Sulawesi Selatan',
  'Kab. Bantaeng, Sulawesi Selatan',
  'Kab. Bulukumba, Sulawesi Selatan',
  'Kab. Sinjai, Sulawesi Selatan',
  'Kab. Kepulauan Selayar, Sulawesi Selatan',

  // Sulawesi Tenggara
  'Kota Kendari, Sulawesi Tenggara',
  'Kota Baubau, Sulawesi Tenggara',
  'Kab. Konawe, Sulawesi Tenggara',
  'Kab. Konawe Selatan, Sulawesi Tenggara',
  'Kab. Konawe Utara, Sulawesi Tenggara',
  'Kab. Konawe Kepulauan, Sulawesi Tenggara',
  'Kab. Kolaka, Sulawesi Tenggara',
  'Kab. Kolaka Utara, Sulawesi Tenggara',
  'Kab. Kolaka Timur, Sulawesi Tenggara',
  'Kab. Bombana, Sulawesi Tenggara',
  'Kab. Muna, Sulawesi Tenggara',
  'Kab. Muna Barat, Sulawesi Tenggara',
  'Kab. Buton, Sulawesi Tenggara',
  'Kab. Buton Utara, Sulawesi Tenggara',
  'Kab. Buton Selatan, Sulawesi Tenggara',
  'Kab. Buton Tengah, Sulawesi Tenggara',
  'Kab. Wakatobi, Sulawesi Tenggara',

  // Gorontalo
  'Kota Gorontalo, Gorontalo',
  'Kab. Gorontalo, Gorontalo',
  'Kab. Gorontalo Utara, Gorontalo',
  'Kab. Boalemo, Gorontalo',
  'Kab. Bone Bolango, Gorontalo',
  'Kab. Pohuwato, Gorontalo',

  // Sulawesi Barat
  'Kota Mamuju, Sulawesi Barat',
  'Kab. Mamuju, Sulawesi Barat',
  'Kab. Mamuju Tengah, Sulawesi Barat',
  'Kab. Pasangkayu, Sulawesi Barat',
  'Kab. Polewali Mandar, Sulawesi Barat',
  'Kab. Majene, Sulawesi Barat',
  'Kab. Mamasa, Sulawesi Barat',

  // Maluku
  'Kota Ambon, Maluku',
  'Kota Tual, Maluku',
  'Kab. Maluku Tengah, Maluku',
  'Kab. Maluku Tenggara, Maluku',
  'Kab. Kepulauan Tanimbar, Maluku',
  'Kab. Buru, Maluku',
  'Kab. Buru Selatan, Maluku',
  'Kab. Seram Bagian Barat, Maluku',
  'Kab. Seram Bagian Timur, Maluku',
  'Kab. Maluku Barat Daya, Maluku',
  'Kab. Kepulauan Aru, Maluku',

  // Maluku Utara
  'Kota Ternate, Maluku Utara',
  'Kota Tidore Kepulauan, Maluku Utara',
  'Kab. Halmahera Utara, Maluku Utara',
  'Kab. Halmahera Barat, Maluku Utara',
  'Kab. Halmahera Tengah, Maluku Utara',
  'Kab. Halmahera Selatan, Maluku Utara',
  'Kab. Halmahera Timur, Maluku Utara',
  'Kab. Kepulauan Sula, Maluku Utara',
  'Kab. Pulau Morotai, Maluku Utara',
  'Kab. Pulau Taliabu, Maluku Utara',

  // Papua
  'Kota Jayapura, Papua',
  'Kab. Jayapura, Papua',
  'Kab. Keerom, Papua',
  'Kab. Sarmi, Papua',
  'Kab. Mamberamo Raya, Papua',
  'Kab. Biak Numfor, Papua',
  'Kab. Supiori, Papua',
  'Kab. Kepulauan Yapen, Papua',
  'Kab. Waropen, Papua',

  // Papua Barat
  'Kota Sorong, Papua Barat',
  'Kab. Manokwari, Papua Barat',
  'Kab. Manokwari Selatan, Papua Barat',
  'Kab. Pegunungan Arfak, Papua Barat',
  'Kab. Teluk Bintuni, Papua Barat',
  'Kab. Teluk Wondama, Papua Barat',
  'Kab. Kaimana, Papua Barat',
  'Kab. Fakfak, Papua Barat',

  // Papua Barat Daya
  'Kab. Sorong, Papua Barat Daya',
  'Kab. Sorong Selatan, Papua Barat Daya',
  'Kab. Raja Ampat, Papua Barat Daya',
  'Kab. Tambrauw, Papua Barat Daya',
  'Kab. Maybrat, Papua Barat Daya',

  // Papua Selatan
  'Kab. Merauke, Papua Selatan',
  'Kab. Boven Digoel, Papua Selatan',
  'Kab. Mappi, Papua Selatan',
  'Kab. Asmat, Papua Selatan',

  // Papua Tengah
  'Kab. Nabire, Papua Tengah',
  'Kab. Mimika, Papua Tengah',
  'Kab. Paniai, Papua Tengah',
  'Kab. Dogiyai, Papua Tengah',
  'Kab. Deiyai, Papua Tengah',
  'Kab. Intan Jaya, Papua Tengah',
  'Kab. Puncak, Papua Tengah',
  'Kab. Puncak Jaya, Papua Tengah',

  // Papua Pegunungan
  'Kab. Jayawijaya, Papua Pegunungan',
  'Kab. Lanny Jaya, Papua Pegunungan',
  'Kab. Nduga, Papua Pegunungan',
  'Kab. Tolikara, Papua Pegunungan',
  'Kab. Yahukimo, Papua Pegunungan',
  'Kab. Yalimo, Papua Pegunungan',
  'Kab. Pegunungan Bintang, Papua Pegunungan',
];
