/**
 * Dataset Sekolah (SMA, SMK) & Perguruan Tinggi (PDDikti Kemdiktisaintek) di Indonesia
 */

export const INDONESIAN_UNIVERSITIES: string[] = [
  'Universitas Indonesia (UI)',
  'Universitas Gadjah Mada (UGM)',
  'Institut Teknologi Bandung (ITB)',
  'Universitas Diponegoro (UNDIP)',
  'Universitas Airlangga (UNAIR)',
  'Universitas Brawijaya (UB)',
  'Universitas Padjadjaran (UNPAD)',
  'Institut Teknologi Sepuluh Nopember (ITS)',
  'Universitas Sebelas Maret (UNS)',
  'Universitas Telkom (Telkom University)',
  'Universitas Bina Nusantara (BINUS)',
  'Universitas Hasanuddin (UNHAS)',
  'Universitas Sumatera Utara (USU)',
  'Universitas Pendidikan Indonesia (UPI)',
  'Universitas Negeri Semarang (UNNES)',
  'Universitas Negeri Yogyakarta (UNY)',
  'Universitas Negeri Jakarta (UNJ)',
  'Universitas Negeri Surabaya (UNESA)',
  'Universitas Negeri Malang (UM)',
  'Politeknik Negeri Semarang (POLINES)',
  'Politeknik Negeri Jakarta (PNJ)',
  'Politeknik Negeri Bandung (POLBAN)',
  'Politeknik Elektronika Negeri Surabaya (PENS)',
  'Politeknik Negeri Malang (POLINEMA)',
  'Universitas Islam Indonesia (UII)',
  'Universitas Muhammadiyah Surakarta (UMS)',
  'Universitas Muhammadiyah Yogyakarta (UMY)',
  'Universitas Muhammadiyah Malang (UMM)',
  'Universitas Katolik Indonesia Atma Jaya',
  'Universitas Trisakti',
  'Universitas Tarumanagara (UNTAR)',
  'Universitas Mercu Buana',
  'Universitas Dian Nuswantoro (UDINUS)',
  'Universitas Katolik Soegijapranata (UNIKA)',
  'Universitas Udayana (UNUD)',
  'Universitas Andalas (UNAND)',
  'Universitas Riau (UNRI)',
  'Universitas Syiah Kuala (USK)',
  'Universitas Lampung (UNILA)',
  'Universitas Jenderal Soedirman (UNSOED)',
  'Universitas Lambung Mangkurat (ULM)',
  'Universitas Mulawarman (UNMUL)',
  'Universitas Sam Ratulangi (UNSRAT)',
  'Universitas Mataram (UNRAM)',
];

export const INDONESIAN_SMA: string[] = [
  'SMAN 1 Semarang',
  'SMAN 3 Semarang',
  'SMAN 5 Semarang',
  'SMAN 1 Jakarta',
  'SMAN 8 Jakarta',
  'SMAN 28 Jakarta',
  'SMAN 68 Jakarta',
  'SMAN 3 Bandung',
  'SMAN 5 Bandung',
  'SMAN 1 Bandung',
  'SMAN 3 Yogyakarta',
  'SMAN 1 Yogyakarta',
  'SMAN 1 Surakarta',
  'SMAN 3 Surakarta',
  'SMAN 5 Surabaya',
  'SMAN 1 Surabaya',
  'SMAN 2 Surabaya',
  'SMAN 1 Malang',
  'SMAN 3 Malang',
  'SMAN 1 Medan',
  'SMAN 3 Medan',
  'SMAN 1 Palembang',
  'SMAN 1 Makassar',
  'SMAN 1 Denpasar',
  'SMA Taruna Nusantara Magelang',
  'SMA Labschool Kebayoran',
  'SMA Al-Azhar Pusat',
  'SMA Kolese Loyola Semarang',
  'SMA Kolese De Britto Yogyakarta',
  'SMA Kanisius Jakarta',
  'SMA St. Louis 1 Surabaya',
];

export const INDONESIAN_SMK: string[] = [
  'SMKN 1 Semarang',
  'SMKN 2 Semarang',
  'SMKN 7 Semarang (STEMBA)',
  'SMKN 26 Jakarta',
  'SMKN 1 Jakarta',
  'SMKN 2 Bandung',
  'SMKN 4 Bandung',
  'SMKN 2 Yogyakarta',
  'SMKN 1 Yogyakarta',
  'SMKN 2 Surakarta',
  'SMKN 5 Surakarta',
  'SMKN 1 Surabaya',
  'SMKN 2 Surabaya',
  'SMKN 1 Malang',
  'SMKN 4 Malang',
  'SMKN 1 Singosari',
  'SMKN 1 Denpasar',
  'SMKN 1 Batam',
  'SMKN 1 Makassar',
  'SMKN 1 Medan',
  'SMKN 2 Palembang',
  'SMK Telkom Bandung',
  'SMK Telkom Jakarta',
  'SMK Telkom Malang',
  'SMK Telkom Purwokerto',
  'SMK Mitra Industri MM2100',
  'SMK Raden Umar Said (RUS) Kudus',
];

export const INDONESIAN_ALL_SCHOOLS: string[] = [
  ...INDONESIAN_UNIVERSITIES,
  ...INDONESIAN_SMA,
  ...INDONESIAN_SMK,
];
